name: firebase_performance
description: Flutter plugin for Google Performance Monitoring for Firebase, an app
  measurement solution that monitors traces and HTTP/S network requests on Android and
  iOS.
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_performance
version: 0.3.2

dependencies:
  flutter:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebaseperformance
        pluginClass: FirebasePerformancePlugin
      ios:
        pluginClass: FLTFirebasePerformancePlugin

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=3.3.0"
